version: '3.9'

services: 
  nestapp:
    container_name: nestapp
    image: santi_dev/nestapp
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=mysql
      - PG_HOST=127.0.0.1
      - PG_USER=root
      - PG_PASSWORD=12345678
      - PG_DB=megacorp
      - PG_PORT=3306
#    depends_on:
#      - db
#  db:
#    container_name: db
#    image: mysql:13
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    volumes:
#  - pgdata:/var/lib/postgresql/data
#volumes:
#  pgdata: {}  